### PR TITLE
Impatient Camwyn == Object fix

### PR DESCRIPTION
**Pull request by Camwyn**
Sorry Zach, I'm impatient. Rewrote objects so we can actually have multiple working cats. Also rewrote the cat AI to make it smarter, but they're still dumb about blocks - not smart enough to move around them...

Essentially, only significant change from the POV of other code is I removed the init function from each object. So, instead of calling cat.init(x,y) you call new cat(x,y).

Feel free to tell me I'm off my rocker!
Stephen

### CODE REVIEW

**Comment by Camwyn** [comment]
Sorry about the lack of automerge...dammit!

**Comment by cmcall** [comment]
I wouldn't work too much on the cat. Me and Susan are going to be implementing some pretty serious overhauls this weekend. The current cat is just a placeholder for people working on other aspects of the game that needed one.

**Comment by zcdziura** [comment]
Bahaha your commits are wonderful. No need to appologize, I'm just glad that someone had the same problem that I did!

**Comment by zcdziura** [comment]
See https://github.com/OctopodGames/Rodents-Revenge/pull/28 for pull request. Someone just has to review my changes to make sure I didn't do anything improper.

**Pull request closed without merging**
